# Generated by Django 4.0.5 on 2022-07-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_comentariocontacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='alumno',
        ),
        migrations.DeleteModel(
            name='ComentarioContacto',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador'),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
