# Generated by Django 4.0.5 on 2022-07-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_remove_comentario_alumno_delete_comentariocontacto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='id',
            new_name='id_a',
        ),
    ]
