# Generated by Django 4.0.5 on 2022-08-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='nombre',
            field=models.TextField(max_length=40),
        ),
    ]
