# Generated by Django 4.0.5 on 2022-08-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0013_alter_tours_disponible_alter_tours_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de edición'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de edición'),
        ),
    ]
