# Generated by Django 4.0.5 on 2022-06-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_cursos_imagen_alter_cursos_duracion_hrs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='imagen',
        ),
    ]
