# Generated by Django 4.0.5 on 2022-07-01 13:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_cursos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_act', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('descripcion_act', ckeditor.fields.RichTextField(verbose_name='Actividad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-created'],
            },
        ),
    ]
